AREA-5 - Setup architecture
G-Epitech/DFMTY-AREA pull request #6
Opened 2024-11-26 17:26 UTC by Yann-Masson

The project architecture is now completely setup (Well, it should be...).
Because it's our first time with flutter, It is almost certain that this architecture is not definitive and will evolve in the future.

As you'll see in this PR, a lot of things are from the flutter example app. We'll customize and clean that later. We have to start some other thins soon as possible so that's why I haven't clean up this shit.

2024-11-26 18:55 UTC, Thomaltarix requested changes
Since you're doing architecture, it would be nice not to have to modify it later.

2024-11-26 18:55 UTC, Thomaltarix commented on mobile/pubspec.yaml
You can add the bloc dependencies so that we don't need to modify it later on

2024-11-26 23:44 UTC, TekMath requested changes
Please update your structure with real MVVM (view layers)

2024-11-27 12:29 UTC, Yann-Masson commented
> Since you're doing architecture, it would be nice not to have to modify it later.

As explain in my PR description, we're totally new to Flutter. So this architecture might be update in time.

2024-11-27 12:58 UTC, Yann-Masson commented
> Please update your structure with real MVVM (view layers)

We don't use the _real_ MVVM project structure. We use a custom architecture that suits us best.

2024-11-27 13:38 UTC, Thomaltarix approved these changes

2024-11-27 13:54 UTC, TekMath approved these changes

2024-11-27 13:54 UTC, merged